### ISSUE TITLE
Create or save page

### ISSUE THREAD

**Issue by gaelb80** [alphalemon/AlphaLemonCmsBundle#12]
Cannot add or update a page in cms, return a 404 error.

**Comment by alphalemon** [comment]
Hi,
how are u? Just downloaded the last sandbox and added two pages one for the available templates in alcms environment and everything was fine.

Have you updated to last version? Are we talking about the current AlphaLemon, not the preview release, aren't we?
Thanks

**Comment by gaelb80** [comment]
hi :) fine was quite busy after holliday and dont have time to test :p yes i'm working on sandbox branch master.

I add a custom theme for testing.

Apparently saving is aborted on BEFORE_ADD_PAGE_COMMIT don't know why, no custom listener configured

**Comment by gaelb80** [comment]
Just install new sandbox, can create a page but cannot edit the page properties after

**Comment by gaelb80** [comment]
For my first problem this is the AddPageBlocksListener that cancel the process when calling the populate from AlTemplateManager. Var slotManagers is empty any idea ?

Maybe a problem in my slots or template definition. I create it using yours as template from business website theme

**Comment by alphalemon** [comment]
Please update your sandbox: I've just commited some fixes. 

I'm working now on the porting of AlphaLemon web site from the PR6 to the master one, so I think I'll update frequently.

**Comment by alphalemon** [comment]
I confirm that adding a page works. I think you are doing something wrong with you r custom theme. If this is true, you''ll get some exceptions when you'll update the sandbox

**Comment by gaelb80** [comment]
Surely a pb in my theme, but with default one cannot edit an existing page

**Comment by gaelb80** [comment]
ok just test a little more, as you rely on page modification to save, if i only update seo datas, the AlPage stay unchanged and you rollback transaction.

**Comment by gaelb80** [comment]
Hi, stay connected on irc if you'd like to discuss how i can help you, hope to see you ++

**Comment by gaelb80** [comment]
Just see your message, still online if you want ;)

**Comment by alphalemon** [comment]
Sorry,
read only now. :-) I looked at the tests and that situation is not covered. Actually I'm working on AlphaLemon's website porting and I found some small bugs already fixed (but not commited). I'm working on docs and in the mornig I hope I'd create d anew repo for docs and update the website. 

So, would you like to try to correct that bug? Let me know if you are going to work on it and if you need help. I can connect and chat if required, but I'm not connected all the time so you must ping me by email. Write to info [at] alphalemon [dOt] com.

Let me know

**Comment by gaelb80** [comment]
Hi, i had a few time today so i'm going to look at fixing that bug

**Comment by alphalemon** [comment]
Awesome! Thanks!

**Comment by gaelb80** [comment]
I dive into listeners and managers and there's a lot of work. Each one has the same bug : if nothing updated for related object, seo by exemple, it rollback all the transaction by aborting event so page is not save
If you can connect on IRC in the morning, ping me to discuss how you want to deal with that

in my opinion, you only need to abort event when catching an exception, in other case let event do its life :p
