### ISSUE TITLE
Assets corrupted

### ISSUE THREAD

**Issue by gaelb80** [alphalemon/AlphaLemonCmsBundle#15]
Seems some assets are corrupted :
- the alphalemon logo small-logo.png
- a jqueryui theme image : ui-bg_flat_75_ffffff_40x100.png

**Comment by alphalemon** [comment]
i noticed that but i wasn't sure, now i am. I run the fabpot's fixer and that's the result. I'll restore them tomorrow.

Obviously if u would like to fix simething prs are welcome! :)

**Comment by alphalemon** [comment]
fixed!
