### ISSUE TITLE
How to insert js only in frontend

### ISSUE THREAD

**Issue by gaelb80** [alphalemon/AlphaLemonCmsBundle#16]
I need jquery, but if i include it in theme configuration it conflicts with the cms version
How can i do it ?

**Comment by alphalemon** [comment]
Some assets are required by AlphaLemonCms to work. The vendor assets are saved in https://github.com/alphalemon/ThemeEngineBundle/tree/master/Resources/public/js/vendor, so the idea is to include the assets from that path when required.

Better solutions are welcome!
Let me know if it's clear enough

**Comment by gaelb80** [comment]
That's what i do to solve my pb but what to do when i need a different version ?

**Comment by alphalemon** [comment]
see #23. Let's continue the discussion on that issue, if required.
