### ISSUE TITLE
Routing management for homepage

### ISSUE THREAD

**Issue by gaelb80** [alphalemon/AlphaLemonCmsBundle#19]
The hompage respond on 2 different url: the root http://www.xxx.xx/ and the permalink name http://www.xxx.xx/homepage.

And link generated in html with tinyMCE link select, used the permalink

For SEO it's really bad.

Is it clear enough ?

**Comment by alphalemon** [comment]
Find a bug. Must recreate route _[main language]_[homepage] that points the home [/] route. So now there are two routes that point the home [/]. Is that fixing?

**Comment by alphalemon** [comment]
Actually AlphaLemon CMS has been fixed to generate two internal routes that responds to home page, as follows:

_en_index:
  pattern: /
  defaults: { _controller: AlphaLemonWebSiteBundle:WebSite:show, _locale: en, page: index }

  # Route <<  >> generated for language << en >> and page << index >>
_home:
  pattern: /
  defaults: { _controller: AlphaLemonWebSiteBundle:WebSite:show, _locale: en, page: index }

so there's just a route for homepage. Is this fixing for you?

**Comment by gaelb80** [comment]
Sorry, at this moment I do not really have time to spend on this project. I hope I can help you later when my schedule lightens a little :|

**Comment by alphalemon** [comment]
Ok, no prob! I'll close these opened issue, in case you'll open it again later. Thank you very much for the time you've dedicated on this project since now and hope to hear you soon!
