### ISSUE TITLE
doctrine/common "dev-bugfix as 2.3.0" doesn't work for me

### ISSUE THREAD

**Issue by akarso** [alphalemon/AlphaLemonCmsBundle#26]
I'm not sure if I'm doing anything wrong, but I cannot install cms bundle because it depends on doctrine/common  "dev-bugfix as 2.3.0" branch which cannot be found.

Maybe changing dependency from "doctrine/common": "dev-bugfix as 2.3.0"  to "doctrine/common": "2.3.0" would fix the issue?

**Comment by alphalemon** [comment]
Hi,
I've just tested the packages fetching and it works for me. I've downloaded the last release without vendors from alphalemon.com, the last composer and run the update command.

Did you make something different?

**Comment by akarso** [comment]
Nope, nothing different AFAIK, symfony 2.1.2 without vendors, installed vendors, made changes to composer.json, run update, and the result is:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package doctrine/common dev-bugfix as 2.3.0 could not be fou
nd.
  Problem 2
    - Installation request for alphalemon/alphalemon-cms-bundle dev-master -> sa
tisfiable by alphalemon/alphalemon-cms-bundle dev-master.
    - alphalemon/alphalemon-cms-bundle dev-master requires doctrine/common dev-b
ugfix as 2.3.0 -> no matching package found.
  Problem 3
    - alphalemon/alphalemon-cms-bundle dev-master requires doctrine/common dev-b
ugfix as 2.3.0 -> no matching package found.
    - alphalemon/alphalemon-cms-installer-bundle dev-master requires alphalemon/
alphalemon-cms-bundle dev-master -> satisfiable by alphalemon/alphalemon-cms-bun
dle dev-master.
    - Installation request for alphalemon/alphalemon-cms-installer-bundle dev-ma
ster -> satisfiable by alphalemon/alphalemon-cms-installer-bundle dev-master.
```

Windows 7, XAMPP.

Full composer.json below. Doctrine/common is "2.3.0" because it's the only way for composer to work, otherwise it raises an error "  Problem 1
    - The requested package doctrine/common dev-bugfix as 2.3.0 could not be found."

```
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://apps.alphalemon.com/"
        }
    ],
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.1.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.0.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.1.*",
        "symfony/monolog-bundle": "2.1.*",
        "sensio/distribution-bundle": "2.1.*",
        "sensio/framework-extra-bundle": "2.1.*",
        "sensio/generator-bundle": "2.1.*",
        "jms/security-extra-bundle": "1.2.*",
        "jms/di-extra-bundle": "1.1.*",     
        "imagine/imagine": ">=0.2",
        "propel/propel-bundle": "1.1.x-dev",
        "propel/propel1": "1.6.*",
        "phing/phing": "2.4.*",
        "willdurand/propel-typehintable-behavior": "dev-master",
        "mikey179/vfsstream": "dev-master",
        "alphalemon/alphalemon-bootstrap-bundle": "dev-master",
        "alphalemon/theme-engine-bundle": "dev-master",
        "alphalemon/elfinder-bundle": "dev-master",
        "alphalemon/business-website-theme-bundle": "dev-master",
        "doctrine/common": "2.3.0",     
        "alphalemon/alphalemon-cms-bundle": "dev-master",
        "alphalemon/alphalemon-cms-installer-bundle": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web"
    }
}
```

**Comment by alphalemon** [comment]
Hi,
that composer.json has a mistake: to use the dev-bugfix you must change the repositories section as follows:

"repositories": [
      {
          "type": "composer",
          "url": "http://apps.alphalemon.com/"
      },
      {
          "type": "git",
          "url": "https://github.com/alphalemon/common"
      }
  ]

However the dev-bugfix just fixes a bug that impacts on testing, see https://github.com/doctrine/common/pull/197, so you can safety use the official repo as you did in your composer.json file.

I've tried alphalemon on windows7 using xampp and I've noticed that it is very slowly when working in alcms_dev env while in alcms env it works fine: is that the same for you? Have you find any solution? Feel free to ping me in pvt for this, if you can.

Thanks!

**Comment by akarso** [comment]
Works much better now, thnx!

**Comment by burtwald** [comment]
Hi I would updated your website if possible as I had this problem and it took me a while to find this and get resolved.

Cheers

**Comment by alphalemon** [comment]
Hi,
could you try to install from the v1.0.0-RC AlphaLemon CMS Sandbox branch:

git clone -b v1.0.0-RC https://github.com/alphalemon/AlphaLemonCmsSandbox.git

If you want to use the AlphaLemon CMS bundle in your own app, please point both alphalemon-cms and installer to dev-v1.0.0-RC branch in your composer.json

Let me know if that solves

**Comment by burtwald** [comment]
Thanks for the response, I originally installed symfony then tried to include the AlphaLemon CMS in this application, this was where I had similar problems to this post. As it was a new application I used the Sandbox and this worked as expected.

Cheers
