### ISSUE TITLE
[symfony 2.1]  I have this runtime exception, why ???

### ISSUE THREAD

**Issue by FL0RlAN** [alphalemon/AlphaLemonCmsBundle#33]
Hello, 

I have this runtime exception, why ???

http://florianbrunet.com/forum/erreur_configuration_alphalemon.PNG

I have done this from https://github.com/stfalcon/TinymceBundle : Add StfalconTinymceBundle to your application kernel.

// app/AppKernel.php
<?php
    // ...
    public function registerBundles()
    {
        $bundles = array(
            // ...
            new Stfalcon\Bundle\TinymceBundle\StfalconTinymceBundle(),
        );
    }

and i have done this (sitebundle is the name of my bundle of tinymcebundle)
http://florianbrunet.com/forum/OK%20installation_tiny_mce%20bundle.PNG

Thank you for your help, 

Florian

**Comment by alphalemon** [comment]
Discussion continues here: https://groups.google.com/forum/#!topic/alphalemoncms-users/vCICVc5q5Jk
