### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by gaelb80** [alphalemon/AlphaLemonCmsBundle#9]
Hi, first great simple cms :) Excellent for little site.

Just try it and had to dive in source code to complete installation :)

Let me add some missing information to get it working in documentation :
- If you start from scratch with a new sf2 project you have to install vendor before generating bundle because bundle generator doesn't exists at this time
- As propel start its 2.0 branch you have to spécified the correct version in your deps : version=origin/1.0
- Missing part about creating controller in our own bundle extending FrontendController to handle page display
- you'll have to improve the theme documentation a little bit and i'll create an issue on corresponding bundle for custom folder
- it will be great for community to add an exemple of implementing a contact form by exemple with prerender listener, can give you an exemple if you want

EDIT : add to update bundle versions in deps

That's it, doesn't read all the doc but i think this is the things to improve for an easier integration

**Comment by alphalemon** [comment]
Hi,
AlphaLemon CMS has been heavily refactored so many of the problems noticed are outdated. The CMS is installable again from https://github.com/alphalemon/AlphaLemonCmsSandbox.

The contact form example is awesome, but be sure it works with this release of AlphaLemon CMS. Could you write a doc about it and add it to Resources/docs? That would be amazing!

Thanks

**Comment by alphalemon** [comment]
Check new documentation at https://github.com/alphalemon/alphalemon-docs. Feel free to open a new issue on that repo for missing documentation.
